language: java
jdk:
- oraclejdk8
sudo: required
dist: trusty
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: oCEaMJF6L1AtDP8lU1uEQvSjA+WY6+9UPn4J5OowqK8eEQpXGxF7Jntqr5QeN9QV32wPeRz3u3HNpvfq7TeQqRkSsE36M/IsHs+SRyYf8isB29W496bsPnCrzPORxjwZxW0n82UEsciRAx4kQXA+P/yBI2kD+6rkk3ZwqY2e/ugTnUuxt4Gx65Gps0PWf+SMFEhkBfa/ghypfGsw2WgKF74W2TaR9c+dHKt/LQn+Sm/6I1VDPpjvtlWPu5v7i/Re/yxJ90bBeIKpmLQh7uPLsxNwc72/MHgv67xbkR6WfS11MJvDo86ecnrDDDLjOZJPXzdiJwHz2dy/wAUNIs0xBXk7MPqPbnL3PXIGVuMpfXDrso5VS4SVtAHQw8R2srLIDA4bMe4U99rU6O8y+um9E9rtj6opOrTKITo1Ybx2eWmzVoiqn+ZfFQQGMdE6VET1fY8YuNLJuPTzKuJ1q7Jqw2b2CdmLyBGHcoyJ37ycqxkZNmmgCFmP98QQKcqvTnrg92JFSCgX/+I1JZmbHt6cGJ2v017uCR9yZauqvdBtMDWgPaxU+kNh5i3q9oOI782PDA/z/2yfinitjRBLrIgGyBXy/OFQI7EjUVVQH1MwggRIyzqm42Yp3DyyWymHNkxHI43oOxZHo7iBP0Gh6/UWM7N7ILV4SvU3eEmMlKgsIzI=
  - secure: ntyTt5GF1dVssa8GX14De77/SIdIdZ9Ee6L8OtxHUKBPLktajM2by5FJyWy32tVL/mBPpn/NORWDSunun5fPnL3d/VzJIwZctvXKWqEgRSYbpvcE0ubEYC94P4wJe72DTjONME2qL+1uWzdmI+W6M/hLhaTJsTXGFpd+C1n+p7b6NWOdL67Fs8vY7Wmx579upGxFzBAsWZm11sqkD1WftKgieaHwgb3JmvLHyrq/VcrZsPSzzgzQnAK9lxMhF2CfM7tke5N+lAxQT3spFlkAEl0pD+P5Po9OMrMNDa/TB2TTX5fE6wlKtF+GBw6+R1HmFpluAw2slDcMtZgeG6vBAMqe6x3h+2Mj90dpayegfNWZvhRlK30Kw0oS3FJNU7L0kPkTiAT9zsr63auykBgCdsTC5GnsGY+4zVIIAEQzNFn7srZbotDIrSjRk447+WqKQ9kT0PZIzDEpcBpfb890i0hGY7pu9yWE2Rq2ygAIZKTqsxsrbiXrJIDUkMQLLxZplxP6q6bp29wBo3BbGCfhgD0jqGc4bLV4N6HPnyNCBqU/90oa17XZg5clAP9vgCgMSTBhpt7jnd9FcpIXlUwNCyrjOP/Tx3ayKPrtfN3bHddbKXnxdQ1IHriq95ou25gwIjkpiZH9Gef3sxYb6ybI3gU4sXfHuBw7fhyC6XqNIZw=
